# Generated by Django 3.1.5 on 2021-01-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='subjects',
            name='Teachers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers'),
            preserve_default=False,
        ),
    ]
