# Generated by Django 3.1.5 on 2021-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210127_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'subjects'},
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='Teachers',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects_taken',
            field=models.ManyToManyField(to='teachers.Subjects'),
        ),
    ]
